name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: update bundler
        run: bundle update --bundler
      
      - name: setup
        run: bundle install

      - name: xcodebuild
        run: set -o pipefail && xcodebuild -scheme DeviceKit -destination "platform=iOS Simulator,name=iPhone 12 Pro" -configuration Debug ONLY_ACTIVE_ARCH=YES -enableCodeCoverage YES test

      - name: danger
        run: bundle exec danger
